# Python Basics
## Arithmatic Operations
___

In [21]:
a= 10; b=20 ; print(a+b) ; print(a-b) ; print(a*b); print(a/b) ; print(a%b); print(a>b); print(a<b); print(a==b);

30
-10
200
0.5
10
False
True
False

## Types of Data
__ __
### Types of data are like Integer, Float, String, Boolean - Short form - Int, float, Str, Bool

In [79]:
c= 1.1 ; type(c) # Decimal values counts in float values

float

In [80]:
d=1 ; type(d)  # Regular values counts in Integer values

int

In [81]:
e=True ; type(e) # Boolean values are True and False where the results get in True and False

bool

In [82]:
f="Vinay"; type(f)  # String values can be called as Text values or values in "" , '' ,'''  '''

str

# Data Types - 1) Numbers
## Variables assigning or Data Storing to use it further

In [88]:
x,y,z = 1,2,3 ;  
g,h,i = 1.9,"a","vinay" ;
j=k=l= "last one" ; 
m = ["First", "Second", 3] ;

In [87]:
print(x); print(y); print(z) ; print(g); print(h); print(i) ; print(j) ; print(k); print(l); print(m)

1
2
3
1.9
a
vinay
last one
last one
last one
['First', 'Second', 3]

## Handy helpful function for # list ## 
- del < To delete the values present in string or list
- pop < To delte the last value present in list

In [116]:
m = ["First", "Second", 3] ;  # in list the position start as 0,1,2,3,4 -
del m[0] ;                           #  here at 0 its value is "First" and so on
print(m)                            # here we deleteout value present on 0 position

['Second', 3]

In [117]:
m.pop() ; print (m) # Pop is used to delete the specific value present in list 
    # If you do not define value in bracket it pops out last value present in list

['Second']

In [129]:
m.extend("1"); print(m) # Extend only takes one value in list

['Second', '1', '1', '1', '1']

In [137]:
m.append("One"); print(m) # Append also adds the value and even takes one value

['Second', '1', '1', '1', '1', 'One', 'One', 'One']

In [140]:
m.count('1') # Count function use to count the number characters which has repeated in list

4

In [153]:
m.clear();  print(m) ; # Flush out all the values assigned to a variable

[]

The syntax of the insert() method is

list.insert(i, elem)
Here, elem is inserted to the list at the ith index. All the elements after elem are shifted to the right.

In [154]:
m.insert(0,"1") ; m.insert(2,"3")

In [155]:
print(m)

['1', '3']

In [157]:
m.insert(2,"4") ; m.insert(3,"2"); print(m)

['1', '3', '4', '2', '4']

In [160]:
m.index('3')  
# Index function provide the position of value in list

1

In [161]:
m.remove('4'); print(m)

['1', '3', '2', '4']

In [162]:
m.sort(); print(m)

['1', '2', '3', '4']

Sort function helps to sort data as per alphabets or numeric values by default whereas remove function helps to delete the specific value defind in the bracket.

In [191]:
m.reverse(); print(m) #Reverse all the value position- last number comes at 0 position

['4', '3', '2', '1']

#### Between some Arithmatic and If & Else functions use

In [113]:
if z>y : 
    print("3 is greater than 2") 
else: 
    print("Change the value")
# Complex functions show
#Example 1
if (x+y==3) :
    print("Correct")
else:
    print("Wrong")
#Example 2
# Use of BODMAS (Bracket,of,Division, Multiplication, Addition, Substraction)

if (x-y*x+y/x>=2) :
    print("Correct")
# 1-2*1+2/1 -1+2 = "1"    Lesser than 2
else:
    print("Wrong")
    
#Example 3

3 is greater than 2
Correct
Wrong

## Standard Data types information

__

*Standard Data Types*
*The data stored in memory can be of many types. For example, a person's age is stored as a numeric value and his or her address is stored as alphanumeric characters. Python has various standard data types that are used to define the operations possible on them and the storage method for each of them.*

Python has five standard data types âˆ’

1. Numbers (Variable assigning which is do
2. String
3. List
4. Tuple
5. Dictionary
____

# 2. String data type ## Functions of *str

In [194]:
my_string = "I am Vinay" ; type(my_string)

str

In [198]:
my_string.capitalize() # this function capitalise the first word and rewrite the sentence 
                       # according

'I am vinay'

In [205]:
my_string.casefold()

'i am vinay'

In [206]:
my_string.

SyntaxError: invalid syntax (<ipython-input-206-38ca27aee311>, line 1)

In [ ]:
list.